{{- if .Values.server.enabled -}}
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: NetworkPolicy
metadata:
  name: {{ template "prometheus.server.fullname" . }}
  labels:
    {{- include "prometheus.server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "prometheus.server.matchLabels" . | nindent 6 }}
  ingress:
    - ports:
      - port: 9090
{{- end }}
{{- end }}
